### ISSUE TITLE
[Security] Sanitize SQL parameters

### ISSUE THREAD

**Issue by mavyfaby** [csps/api#12]
### Description

Sanitizing SQL parameters ensured that the values passed in the parameter are safe by removing or escaping any characters that could be interpreted as SQL commands or keywords.

### Task

Make a `sanitize(value: any): string` function that accepts any value and sanitize it and return a string with this instructions in chronological order:

- [x] if `undefined` or `null`, return empty string.
- [x] if `number`, convert it to string.
- [x] encode or escape special characters, such as quotes, semicolons, dashes, or comments.

**Comment by mavyfaby** [comment]
The commit [6462989](https://github.com/csps/api/commit/6462989f3d1b640b99a2ca132cddafa8ae5d0e8a) solved this issue.
